# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/user/AppData/Local/Temp/SplashScreenSIcMYx.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(490, 350)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"\n"
"    background-color: rgb(56, 58, 89);\n"
"color: rgb(220, 220, 220);\n"
"border-radius: 10px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_AppName = QtWidgets.QLabel(self.frame)
        self.label_AppName.setGeometry(QtCore.QRect(6, 60, 441, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(36)
        self.label_AppName.setFont(font)
        self.label_AppName.setStyleSheet("color: rgb(200, 95, 155);")
        self.label_AppName.setAlignment(QtCore.Qt.AlignCenter)
        self.label_AppName.setObjectName("label_AppName")
        self.label_AppName2 = QtWidgets.QLabel(self.frame)
        self.label_AppName2.setGeometry(QtCore.QRect(10, 130, 441, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_AppName2.setFont(font)
        self.label_AppName2.setStyleSheet("color: rgb(113, 125, 200);")
        self.label_AppName2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_AppName2.setObjectName("label_AppName2")
        self.label_progressBar = QtWidgets.QProgressBar(self.frame)
        self.label_progressBar.setGeometry(QtCore.QRect(40, 240, 421, 23))
        self.label_progressBar.setStyleSheet("QProgressBar{\n"
"background-color: rgb(98, 114, 164);\n"
"    color: rgb(200, 200, 200);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(254, 121, 199, 255), stop:1 rgba(170, 85, 255, 255));\n"
"      }")
        self.label_progressBar.setProperty("value", 24)
        self.label_progressBar.setObjectName("label_progressBar")
        self.label_loading = QtWidgets.QLabel(self.frame)
        self.label_loading.setGeometry(QtCore.QRect(20, 270, 451, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_loading.setFont(font)
        self.label_loading.setStyleSheet("color: rgb(113, 125, 200);")
        self.label_loading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_loading.setObjectName("label_loading")
        self.label_MyName = QtWidgets.QLabel(self.frame)
        self.label_MyName.setGeometry(QtCore.QRect(20, 300, 431, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_MyName.setFont(font)
        self.label_MyName.setStyleSheet("color: rgb(113, 125, 200);")
        self.label_MyName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_MyName.setObjectName("label_MyName")
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_AppName.setText(_translate("MainWindow", "<strong>FACE </strong>RECOGNITION"))
        self.label_AppName2.setText(_translate("MainWindow", "<strong>ATTENDANCE </strong>SYSTEM"))
        self.label_loading.setText(_translate("MainWindow", "Loading....."))
        self.label_MyName.setText(_translate("MainWindow", "<strong>Created by </strong>Jazi Safa"))
